apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka
spec:
  kafka:
    example:
      # kafka broker url
      url: b-1-public.debug.xmrl2t.c2.kafka.eu-west-1.amazonaws.com:9196,b-3-public.debug.xmrl2t.c2.kafka.eu-west-1.amazonaws.com:9196,b-2-public.debug.xmrl2t.c2.kafka.eu-west-1.amazonaws.com:9196
      topic: my_new_topic
      jsonBody: true
      partition: "0"
      sasl:
        mechanism: OAUTHBEARER
        userSecret:
          key: user
          name: msk-secret
        passwordSecret:
          key: password
          name: msk-secret
